stages:
  prepare_data_shallow:
    cmd: python -m pipeline_shallow.stage_prepare_data
    deps:
    - pipeline_shallow/stage_prepare_data.py
    - data/child-mind-institute-problematic-internet-use/train.csv
    - data/child-mind-institute-problematic-internet-use/test.csv
    - data/child-mind-institute-problematic-internet-use/series_train.parquet
    - data/child-mind-institute-problematic-internet-use/series_test.parquet
    params:
    - prepare_data.var_target
    - prepare_data.vars_cat
    - prepare_data.vars_num
    outs:
    - output/train_processed.csv
    - output/test_processed.csv
  train_shallow:
    cmd: python -m pipeline_shallow.stage_train
    deps:
    - pipeline_shallow/stage_train.py
    - output/train_processed.csv
    - output/test_processed.csv
    params:
    - prepare_data.var_target
    - prepare_data.vars_cat
    - prepare_data.vars_num
    outs:
    - output/submission.csv
    - output/labels_filled.csv


  prepare_data_deep:
    cmd: python -m pipeline_deep.stage_write_tfrecords
    deps:
    - pipeline_deep/stage_write_tfrecords.py
    - pipeline_deep/data_preparation/tfrecord_manager.py
    - pipeline_deep/data_preparation/tfrecord_manager_child_mind.py
    - data/child-mind-institute-problematic-internet-use/train.csv
    - data/child-mind-institute-problematic-internet-use/test.csv
    - data/child-mind-institute-problematic-internet-use/series_train.parquet
    - data/child-mind-institute-problematic-internet-use/series_test.parquet
    - output/labels_filled.csv
    params:
    - prepare_data.n_cols_ts
    - prepare_data.n_rows_ts
    outs:
    - output/tfrecords/
  train_deep:
    cmd: python -m pipeline_deep.stage_train
    deps:
    - pipeline_deep/stage_train.py
    - output/tfrecords/
    params:
    - train.n_epochs
    - train.batch_size
