prepare_data:
  path_tabular_train: data/child-mind-institute-problematic-internet-use/train.csv
  path_tabular_test: data/child-mind-institute-problematic-internet-use/test.csv
  path_series_train: data/child-mind-institute-problematic-internet-use/series_train
  path_series_test: data/child-mind-institute-problematic-internet-use/series_test
  path_output: output/
  n_examples_per_file_train: 10
  n_examples_per_file_submit: 10
  # Kaggle paths:
  # - path_train_raw: /kaggle/input/child-mind-institute-problematic-internet-use/train.csv
  # - path_test_raw: /kaggle/input/child-mind-institute-problematic-internet-use/test.csv
  vars_num:
    - Basic_Demos-Age
    - Basic_Demos-Sex
    - CGAS-CGAS_Score
    - Physical-BMI
    - Physical-Height
    - Physical-Weight
    - Physical-Waist_Circumference
    - Physical-Diastolic_BP
    - Physical-HeartRate
    - Physical-Systolic_BP
    - Fitness_Endurance-Max_Stage
    - Fitness_Endurance-Time_Mins
    - Fitness_Endurance-Time_Sec
    - FGC-FGC_CU
    - FGC-FGC_CU_Zone
    - FGC-FGC_GSND
    - FGC-FGC_GSND_Zone
    - FGC-FGC_GSD
    - FGC-FGC_GSD_Zone
    - FGC-FGC_PU
    - FGC-FGC_PU_Zone
    - FGC-FGC_SRL
    - FGC-FGC_SRL_Zone
    - FGC-FGC_SRR
    - FGC-FGC_SRR_Zone
    - FGC-FGC_TL
    - FGC-FGC_TL_Zone
    - BIA-BIA_Activity_Level_num
    - BIA-BIA_BMC
    - BIA-BIA_BMI
    - BIA-BIA_BMR
    - BIA-BIA_DEE
    - BIA-BIA_ECW
    - BIA-BIA_FFM
    - BIA-BIA_FFMI
    - BIA-BIA_FMI
    - BIA-BIA_Fat
    - BIA-BIA_Frame_num
    - BIA-BIA_ICW
    - BIA-BIA_LDM
    - BIA-BIA_LST
    - BIA-BIA_SMM
    - BIA-BIA_TBW
    - PAQ_A-PAQ_A_Total
    - PAQ_C-PAQ_C_Total
    - SDS-SDS_Total_Raw
    - SDS-SDS_Total_T
    - PreInt_EduHx-computerinternet_hoursday
  vars_cat:
    - Basic_Demos-Enroll_Season
    - CGAS-Season
    - Physical-Season
    - Fitness_Endurance-Season
    - FGC-Season
    - BIA-Season
    - PAQ_A-Season
    - PAQ_C-Season
    - SDS-Season
    - PreInt_EduHx-Season
  var_target: sii
