stages:
  prepare_data:
    cmd: python -m step_prepare_data
    deps:
    - step_prepare_data.py
    params:
    - prepare_data.var_target
    - prepare_data.vars_cat
    - prepare_data.vars_num
    outs:
    - ../output/test_processed.csv
    - ../output/train_processed.csv
  train:
    cmd: python -m step_train
    deps:
    - step_train.py
    params:
    - prepare_data.var_target
    - prepare_data.vars_cat
    - prepare_data.vars_num
    outs:
    - ../output/submission.csv